; Erik Torres
; THIS PROGRAM CONFIGURES T0 AND T1 TO TIMERS, T0 IS CONFIGURED TO MODE 1 AND T1 IS CONFIGURED TO MODE 2.
; IT ALSO CONFIGURES THE SERIAL PORT TO MODE 1 WITH RECEPTION ENABLED AND WITH A 9600 BAUD RATE.
; THE SERIAL PORT OPERATION RECEIVES A ASCII CHARACTER AND THE CHARACTER GETS INCREMENTED AND THEN IT GETS TRANSMITTED BACK TO THE TERMINAL.
; EACH TIME T0 OVERFLOWS THE INPUT PORT P1 IS COMPLEMENTED AND READ INTO OUTPUT PORT P2.

					ORG				0; START AT ORIGINATE 0
					JMP				MAIN; JUMP TO MAIN
					ORG				50H; MAIN IS LOCATED AT 50H
					MAIN:
					MOV				TMOD, #21H; CONFIGURE T0 IN MODE 1 AND T1 IN MODE 2
					MOV				TH1, #-3; BAUD RATE 9600 BPS(BITS PER SECOND)
					SETB			SM1; SERIAL MODE 1 (UART)
					SETB			REN; ENABLE RECEPTION
					MOV				P2,#0; CONFIGURE PORT2 AS OUTPUT
					SETB			TR0; START T0
					SETB			TR1; START T1
						
					JNB				RI, $; POLLING WAIT FOR A RECEIVED CHARACTER
					CLR				RI; CLEAR RECEIVE INTERRUPT FLAG
					MOV				A,SBUF; MOVE THE RECEIVED CHARACTER TO A
					INC				A; INCREMENT A
					MOV				SBUF, A; WE THEN ECHO BACK THAT CHARACTER AND TRANSMIT THE CHARACTER
					JNB				TI,$; SINCE WE PUT SOMETHING IN SBUF WE HAVE TO POLL AND WAIT UNTIL TRANSMITION PROCESS IS DONE
					CLR				TI ; CLEAR TRANSMIT INTERRUPT FLAG
						
					JNB				TF0,$; WAIT ON TIMER 0 ONCE OV GO TO LINES BELOW
					CPL				A; COMPLEMENT A
					MOV				P1,A; MOVE A INTO P1
					MOV				P2,P1; DISPLAY DATA IN P1 IN P2
					CLR				TF0; CLEAR TIMER OV FLAG
					END
